Traceback (most recent call last):
  File "/opt/letsencrypt/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.0', 'console_scripts', 'letsencrypt')()
  File "/opt/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1251, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/opt/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1164, in setup_logging
    args, logfile=logfile, fmt=fmt)
  File "/opt/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1135, in setup_log_file_handler
    log_file_path, maxBytes=2 ** 20, backupCount=10)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
